# Generated by Django 5.0.4 on 2024-07-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_rename_devices_device"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="type",
            field=models.CharField(
                choices=[
                    ("Mobile Phone", "Mobile Phone"),
                    ("Tablet", "Tablet"),
                    ("Smart Watch", "Smart Watch"),
                    ("Not Specified", "Not Specified"),
                ],
                default="Not Specified",
                max_length=50,
            ),
        ),
    ]
